name: skeleton_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^11.0.0
  flutter_svg: ^2.3.0
  fluttertoast: ^10.0.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.1
  google_fonts: ^8.2.1
  injectable: ^3.0.0
  json_annotation: ^4.12.0
  shared_preferences: ^2.5.5
  retrofit: ^4.9.0
  logger: ^2.6.0 
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^9.1.1
  shimmer: ^4.0.0
  flutter_localization: ^0.4.1
  cached_network_image: ^3.4.1
  auto_size_text: ^3.0.0
  dio: ^5.11.1
  provider: ^6.1.5+1
  mobile_scanner: ^7.4.2
  image_picker: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: ^10.0.1
  json_serializable: ^6.10.0
  injectable_generator: ^3.1.1
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.6.0
  freezed: ^3.0.0


flutter:
  generate: true 
  uses-material-design: true
  assets:
    - assets/images/
flutter_assets:
  assets_path: assets/
  output_path: lib/core/theming/
  filename: assets.dart
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
